runtime: nodejs16
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: 'production'
  JWT_SECRET_KEY: 'your_jwt_secret_key'
  DB_HOST: '/cloudsql/YOUR_INSTANCE_CONNECTION_NAME'
  DB_USER: 'your_db_username'
  DB_PASSWORD: 'your_db_password'
  DB_NAME: 'newsletter'
  SENDGRID_API_KEY: 'undefined'
  
beta_settings:
  cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME